services:
  - type: web
    name: hostwatch-backend
    runtime: docker
    rootDir: back
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: pgsql
      - key: QUEUE_CONNECTION
        value: sync
      - key: DB_URL
        fromDatabase:
          name: hostwatch-db
          property: connectionString
databases:
  - name: hostwatch-db
    plan: free
